### ISSUE TITLE
resource intersight_appliance_device_claim doesn't work 

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/terraform-provider-intersight#12]
When I am trying to claim a C-series appliance in intersight using claim-code and device_id, "terraform plan" works but "terraform apply" fails to claim the device. 

**terraform plan**
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
-----------------------------------------------------------------------
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # intersight_appliance_device_claim.appliance_device_claim will be created
  + resource "intersight_appliance_device_claim" "appliance_device_claim" {
      + account         = (known after apply)
      + class_id        = (known after apply)
      + device_id       = "xxxxxxxx"
      + id              = (known after apply)
      + is_password_set = (known after apply)
      + message         = (known after apply)
      + moid            = (known after apply)
      + object_type     = (known after apply)
      + security_token  = "xxxxxxxxxxx"
      + status          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

**TF_LOG=TRACE terraform apply** 
2020-11-25T12:19:38.691-0800 [DEBUG] plugin.terraform-provider-intersight_v0.1.0: 
2020-11-25T12:19:38.691-0800 [DEBUG] plugin.terraform-provider-intersight_v0.1.0: {"code":"InvalidUrl","message":"Operation not supported. Check if the API path and method are valid.","messageId":"iam_invalid_method_operation","messageParams":{},"traceId":"NB50f980c1d45c0a333731bdd73e082c7d"}
2020-11-25T12:19:38.691-0800 [DEBUG] plugin.terraform-provider-intersight_v0.1.0: 
2020/11/25 12:19:38 [DEBUG] intersight_appliance_device_claim.appliance_device_claim: apply errored, but we're indicating that via the Error pointer rather than returning it: Failed to invoke operation: undefined response type
2020/11/25 12:19:38 [TRACE] eval: *terraform.EvalMaybeTainted
2020/11/25 12:19:38 [TRACE] EvalMaybeTainted: intersight_appliance_device_claim.appliance_device_claim encountered an error during creation, so it is now marked as tainted
2020/11/25 12:19:38 [TRACE] eval: *terraform.EvalWriteState

2020/11/25 12:19:38 [ERROR] eval: *terraform.EvalApplyPost, err: Failed to invoke operation: undefined response type
2020/11/25 12:19:38 [ERROR] eval: *terraform.EvalSequence, err: Failed to invoke operation: undefined response type
2020/11/25 12:19:38 [TRACE] [walkApply] Exiting eval tree: intersight_appliance_device_claim.appliance_device_claim
2020/11/25 12:19:38 [TRACE] vertex "intersight_appliance_device_claim.appliance_device_claim": visit complete
2020/11/25 12:19:38 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/11/25 12:19:38 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/ciscodevnet/intersight\"] (close)" errored, so skipping

2020/11/25 12:19:38 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
Error: Failed to invoke operation: undefined response type

  on claim_device.tf line 1, in resource "intersight_appliance_device_claim" "appliance_device_claim":
   1: resource "intersight_appliance_device_claim" "appliance_device_claim" {

2020-11-25T12:19:38.715-0800 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/ciscodevnet/intersight/0.1.0/darwin_amd64/terraform-provider-intersight_v0.1.0 pid=77749
2020-11-25T12:19:38.715-0800 [DEBUG] plugin: plugin exited

**Comment by sandkum5** [comment]
Using the following config for the resource: 

resource "intersight_appliance_device_claim" "appliance_device_claim" {
  device_id      = "xxxxxxxx"
  security_token = "xxxxxxxxxx"
}

**Comment by vvb** [comment]
Hi @sandkum5 

Thanks for posting this issue.
The error seems to suggest an invalid endpoint url

Can you also attach the endpoint configured in the provider section.

**Comment by sandkum5** [comment]
Hi, 

Here is the provider config: 

cat provider.tf 
terraform {
  required_providers {
    intersight = {
      source  = "CiscoDevNet/intersight"
      version = "0.1.0"
    }
  }
}

provider "intersight" {
  apikey        = var.api_key
  secretkeyfile = "SecretKey.txt"
  endpoint      = "https://intersight.com"
}

**Comment by code-lucidal58** [comment]
Fixed in 0.1.2

**Comment by sandkum5** [comment]
I am still seeing this issue with Version 1.0.2

resource "intersight_appliance_device_claim" "appliance_device_claim" {
  device_id      = "yyyyyyyy"
  security_token = "xxxxxxx"
}


% terraform apply  

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # intersight_appliance_device_claim.appliance_device_claim will be created
  + resource "intersight_appliance_device_claim" "appliance_device_claim" {
      + account         = (known after apply)
      + class_id        = (known after apply)
      + device_id       = "yyyyyyyy"
      + id              = (known after apply)
      + is_password_set = (known after apply)
      + is_renew        = false
      + message         = (known after apply)
      + moid            = (known after apply)
      + object_type     = (known after apply)
      + security_token  = "xxxxxx"
      + status          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

intersight_appliance_device_claim.appliance_device_claim: Creating...

Error: failed while creating ApplianceDeviceClaim: undefined response type Response from endpoint: {"code":"InvalidUrl","message":"Operation not supported. Check if the API path and method are valid.","messageId":"iam_invalid_method_operation","messageParams":{},"traceId":"NB441597ea1fc2be1de409de4230d16b96"}

**Comment by jicoyne** [comment]
I have the same issue. Can not claim devices, Operation not supported.

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of ciscodevnet/intersight from the dependency lock file
- Using previously-installed hashicorp/aws v3.31.0
- Using previously-installed ciscodevnet/intersight v1.0.2

___

resource "intersight_appliance_device_claim" "appliance_device_claim" {

  device_id ="FCH2017VXXX"
  security_token = "E50D3D159XXX"
  is_renew = false

___

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

  + create

Terraform will perform the following actions:

  + resource "intersight_appliance_device_claim" "appliance_device_claim" {
      + account         = (known after apply)
      + class_id        = (known after apply)
      + device_id       = "FCH2017VXXX"
      + id              = (known after apply)
      + is_password_set = (known after apply)
      + is_renew        = false
      + message         = (known after apply)
      + moid            = (known after apply)
      + object_type     = (known after apply)
      + security_token  = "E50D3D159XXX"
      + status          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

intersight_appliance_device_claim.appliance_device_claim: Creating...

Error: failed while creating ApplianceDeviceClaim: undefined response type Response from endpoint: {"code":"InvalidUrl","message":"Operation not supported. Check if the API path and method are valid.","messageId":"iam_invalid_method_operation","messageParams":{},"traceId":"NBd62f270fa68824a2b4ee3d0ef3e97c0c"}
